### ISSUE TITLE
No dialect with MSsql 

### ISSUE THREAD

**Issue by jrobens** [DiUS/java-faker#261]
I am using jdbc:sqlserver: with dialect: org.hibernate.dialect.SQLServer2012Dialect and getting the following stack trace.

`
java.lang.NoSuchMethodException: org.hibernate.jpa.internal.metamodel.MetamodelImpl.entityPersisters()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.github.kuros.random.jpa.util.Util.invokeMethod(Util.java:165)
	at com.github.kuros.random.jpa.metamodel.providers.hibernate.v5.HibernateProviderV5.getMetaDataMap(HibernateProviderV5.java:37)
	at com.github.kuros.random.jpa.metamodel.providers.hibernate.HibernateProviderBase.init(HibernateProviderBase.java:52)
	at com.github.kuros.random.jpa.metamodel.providers.hibernate.v5.HibernateProviderV5.<init>(HibernateProviderV5.java:32)
	at com.github.kuros.random.jpa.metamodel.AttributeProviderFactory.getProvider(AttributeProviderFactory.java:21)
	at com.github.kuros.random.jpa.cache.Cache.initAttributeProvider(Cache.java:127)
	at com.github.kuros.random.jpa.cache.Cache.<init>(Cache.java:54)
	at com.github.kuros.random.jpa.cache.Cache.create(Cache.java:64)
	at com.github.kuros.random.jpa.JPAContextFactory.getCache(JPAContextFactory.java:111)
	at com.github.kuros.random.jpa.JPAContextFactory.generate(JPAContextFactory.java:105)
	at my.package.integration.CreditPaymentInstructionChqJobTest.test(CreditPaymentInstructionChqJobTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

javax.persistence.PersistenceException: org.hibernate.MappingException: No Dialect mapping for JDBC type: -9

	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:372)
	at com.sun.proxy.$Proxy119.getResultList(Unknown Source)
	at com.github.kuros.random.jpa.provider.base.AbstractMultiplePrimaryKeyProvider.init(AbstractMultiplePrimaryKeyProvider.java:45)
	at com.github.kuros.random.jpa.provider.base.AbstractMultiplePrimaryKeyProvider.<init>(AbstractMultiplePrimaryKeyProvider.java:40)
	at com.github.kuros.random.jpa.provider.mssql.MSSQLMultiplePrimaryKeyProvider.<init>(MSSQLMultiplePrimaryKeyProvider.java:41)
	at com.github.kuros.random.jpa.provider.mssql.MSSQLMultiplePrimaryKeyProvider.getInstance(MSSQLMultiplePrimaryKeyProvider.java:50)
	at com.github.kuros.random.jpa.provider.factory.MultiplePrimaryKeyProviderFactory.getMultiplePrimaryKeyProvider(MultiplePrimaryKeyProviderFactory.java:37)
	at com.github.kuros.random.jpa.cache.Cache.initMultiplePrimaryKeyProvider(Cache.java:123)
	at com.github.kuros.random.jpa.cache.Cache.<init>(Cache.java:55)
	at com.github.kuros.random.jpa.cache.Cache.create(Cache.java:64)
	at com.github.kuros.random.jpa.JPAContextFactory.getCache(JPAContextFactory.java:111)
	at com.github.kuros.random.jpa.JPAContextFactory.generate(JPAContextFactory.java:105)
	at my.package.integration.CreditPaymentInstructionChqJobTest.test(CreditPaymentInstructionChqJobTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.hibernate.MappingException: No Dialect mapping for JDBC type: -9
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:70)
	at org.hibernate.dialect.TypeNames.get(TypeNames.java:101)
	at org.hibernate.dialect.Dialect.getHibernateTypeName(Dialect.java:666)
	at org.hibernate.loader.custom.JdbcResultMetadata.getHibernateType(JdbcResultMetadata.java:77)
	at org.hibernate.loader.custom.ScalarResultColumnProcessor.performDiscovery(ScalarResultColumnProcessor.java:45)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:487)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2125)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1900)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1876)
	at org.hibernate.loader.Loader.doQuery(Loader.java:919)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:336)
	at org.hibernate.loader.Loader.doList(Loader.java:2617)
	at org.hibernate.loader.Loader.doList(Loader.java:2600)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2429)
	at org.hibernate.loader.Loader.list(Loader.java:2424)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:336)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:1967)
	at org.hibernate.internal.AbstractSessionImpl.list(AbstractSessionImpl.java:322)
	at org.hibernate.internal.SQLQueryImpl.list(SQLQueryImpl.java:125)
	at org.hibernate.jpa.internal.QueryImpl.list(QueryImpl.java:606)
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:483)
	... 45 more`

**Comment by PascalSchumacher** [comment]
No sure where this should be reported (Hibernate?), but this is the wrong project. Java faker does not deal with jpa/sql.
