### ISSUE TITLE
Zip code by state 

### ISSUE THREAD

**Issue by ademdogu** [DiUS/java-faker#293]
`faker.address().zipCodeByState("AZ")`

errors out:
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
	at com.github.javafaker.service.FakeValuesService.fetchObject(FakeValuesService.java:220)
	at com.github.javafaker.service.FakeValuesService.safeFetch(FakeValuesService.java:190)
	at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:332)
	at com.github.javafaker.Address.zipCodeByState(Address.java:38)
```

**Comment by ademdogu** [comment]
ah, thanks!
