### ISSUE TITLE
idNumber().ssnValid() throws NoSuchMethodError

### ISSUE THREAD

**Issue by randysecrist** [DiUS/java-faker#298]
Using version 0.15

```
scala> import com.github.javafaker.Faker
import com.github.javafaker.Faker

scala> import java.util.Locale
import java.util.Locale

scala> val f = new Faker(new Locale("en-US"))
f: com.github.javafaker.Faker = com.github.javafaker.Faker@27d9146d

scala> f.idNumber().ssnValid()
java.lang.NoSuchMethodError: com.mifmif.common.regex.Generex.setSeed(J)V
  at com.github.javafaker.service.FakeValuesService.regexify(FakeValuesService.java:279)
  at com.github.javafaker.Faker.regexify(Faker.java:256)
  at com.github.javafaker.idnumbers.EnIdNumber.getValidSsn(EnIdNumber.java:14)
  at com.github.javafaker.IdNumber.ssnValid(IdNumber.java:23)
  ... 43 elided
```

**Comment by randysecrist** [comment]
This no longer seems to be a problem now that there has been a release > 0.15.  Closing.
