### ISSUE TITLE
Initialization of faker failing with the latest release

### ISSUE THREAD

**Issue by PeskyTheBear** [DiUS/java-faker#349]
Hello,
I'm using the latest release (0.17.1) downloaded from maven central but every time i try to make a new instance of the faker i am getting te following error 
```
Caused by: java.lang.NullPointerException
	at com.github.javafaker.service.FakeValuesService.<init>(FakeValuesService.java:82) [javafaker-0.17.1.jar:]
	at com.github.javafaker.Faker.<init>(Faker.java:101) [javafaker-0.17.1.jar:]
	at com.github.javafaker.Faker.<init>(Faker.java:92) [javafaker-0.17.1.jar:]
	at com.github.javafaker.Faker.<init>(Faker.java:88) [javafaker-0.17.1.jar:]
```

The faker is instantiated without any parameters in the constructor

**Comment by codingricky** [comment]
@PeskyTheBear how are you creating the Faker object? Which params are you passing in? and which version of the JVM are you using?

**Comment by thomhurst** [comment]
I'm also getting this! Java 8, Windows 10, Android Codebase using Kotlin

**Comment by codingricky** [comment]
I did a release 0.17.2 that should support android
