### ISSUE TITLE
Make it compatible with android

### ISSUE THREAD

**Issue by EmmanuelVinas** [DiUS/java-faker#440]
**Is your feature request related to a problem? Please describe.**
I tried to use faker for a mock flavor in android 9 but got a crash 

Can't initialize a Faker() due to that exception. 
```
   java.lang.ExceptionInInitializerError
        at com.github.javafaker.Faker.<init>(Faker.java:111)
        at com.github.javafaker.Faker.<init>(Faker.java:102)
        at com.github.javafaker.Faker.<init>(Faker.java:98)
...
Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 52
    #\{([a-z0-9A-Z_.]+)\s?(?:'([^']+)')?(?:,'([^']+)')*}```

**Comment by Tavo5691** [comment]
Hi @EmmanuelVinas, your PR seems to have fixed the issue and is included in version 1.0.2. 

Maybe we can close this issue.
