### ISSUE TITLE
Initialization of Faker (v1.0.1) failing in Android Kotlin project

### ISSUE THREAD

**Issue by medihack** [DiUS/java-faker#454]
Using Faker version 1.0.1 with an Android project (Android Studio, Kotlin Codebase, Java 8, Windows 10) I get the following error while initializing Faker (`val faker = Faker()`):

<pre>
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: tools.meaky.dearapp, PID: 11736
    java.lang.ExceptionInInitializerError
        at com.github.javafaker.Faker.<init>(Faker.java:111)
        at com.github.javafaker.Faker.<init>(Faker.java:102)
        at tools.meaky.dearapp.debug.DebugDbPopulator.populate(DebugDbPopulator.kt:15)
        at tools.meaky.dearapp.data.AppDatabase$Companion$buildDatabase$1.onCreate(AppDatabase.kt:39)
        at tools.meaky.dearapp.data.AppDatabase_Impl$1.onCreate(AppDatabase_Impl.java:58)
        at androidx.room.RoomOpenHelper.onCreate(RoomOpenHelper.java:87)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onCreate(FrameworkSQLiteOpenHelper.java:118)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:393)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
        at androidx.room.RoomDatabase.query(RoomDatabase.java:300)
        at tools.meaky.dearapp.MyApplication.onCreate(MyApplication.kt:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 52
    #\{([a-z0-9A-Z_.]+)\s?(?:'([^']+)')?(?:,'([^']+)')*}
                                                        ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:1344)
        at java.util.regex.Pattern.<init>(Pattern.java:1328)
        at java.util.regex.Pattern.compile(Pattern.java:950)
        at com.github.javafaker.service.FakeValuesService.<clinit>(FakeValuesService.java:25)
        	... 23 more
</pre>

**Comment by OLEG4120** [comment]
The same error as in 440?
https://github.com/DiUS/java-faker/issues/440

**Comment by ch8n** [comment]
Hey, @OLEG4120 @medihack, I manually tried to import the library to android and I was able to initialize faker with `Faker()` object without any exception, for this, I had to convert maven project to Gradle project then import it into the android studio using Java module.

I'm new to open source contribution so can you help me out how I could put any procedure/code to make it running?

**Comment by Tavo5691** [comment]
Hi @medihack, is this still an issue for you? 

Version 1.0.2 should contain PR #443 which should have fixed the problem. Please try to confirm so we can close the issue.

**Comment by medihack** [comment]
Seems to work, thanks! Closing the issue.
