### ISSUE TITLE
Resolving an expression that is a named composite of other fields throws exception

### ISSUE THREAD

**Issue by jwatkinsdavid-scottlogic** [DiUS/java-faker#474]
**Describe the bug**
When calling the 'expression' method on the 'Faker' class using an expression that is a directive which is composed of one or more other directives within the fake definition YAML, (e.g. "#{job.title}"), the FakeValueService throws an exception:

```
Exception in thread "main" java.lang.RuntimeException: Unable to resolve #{seniority} directive.
	at com.github.javafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:360)
	at com.github.javafaker.service.FakeValuesService.resolveExpression(FakeValuesService.java:363)
	at com.github.javafaker.service.FakeValuesService.expression(FakeValuesService.java:322)
	at com.github.javafaker.Faker.expression(Faker.java:653)
```

**To Reproduce**

```
Faker faker = new Faker();
String jobTitle = faker.expression("#{job.title}");
```

**Expected behavior**
The requested fake value is returned.

In the example above for 'job.title' this will be a string containing the combined elements of a job title (seniority, field, position)

**Versions:**
 - OS: Windows 10
 - JDK: 1.8
 - Faker Version [e.g. 22]: 1.0.2

**Additional context**
This appears to be a general issue with any expressions that use definitions that are composed from other definitions as this can be replicated with the following other expressions:

```
faker.expression("#{name.first_name}");
faker.expression("#{name.name_with_middle}");
```

**Comment by jwatkinsdavid-scottlogic** [comment]
This appears to only be an issue when the 'sub-directive' that is used is not prefixed with the appropriate 'owner' because the 'owner' is the same as the directive.

e.g. In name.yml:

```
name:
        - "#{prefix} #{first_name} #{last_name}"
        - "#{first_name} #{last_name} #{suffix}"
        - "#{first_name} #{last_name}"
        - "#{first_name} #{last_name}"
        - "#{first_name} #{last_name}"
        - "#{first_name} #{last_name}"
```

If the above all contained a 'job' prefix then they resolve as expected.

When the 'owner' is different then the directive is prefixed and this works as expected.

e.g. In book.yml

`author: "#{Name.name}"`

This means that there are two ways to resolve this:

1. Ensure that the sub-directives used in the YML files always contain a prefix
2. Update the directive resolution process to use an appropriate prefix when de-referencing directives composed of other directives
