### ISSUE TITLE
Throwing Error when generate a fixed length internet password

### ISSUE THREAD

**Issue by siutin** [DiUS/java-faker#498]
**Describe the bug**
Trying to generate a fixed length password include uppercase, special characters and digits.

**To Reproduce**
```
Faker.instance().internet().password(32, 32, true, true, true)
```

**Expected behavior**
Return a password correctly

**Result**

```
java.lang.IllegalArgumentException: bound must be positive

	at java.base/java.util.Random.nextInt(Random.java:388)
	at com.github.javafaker.service.RandomService.nextInt(RandomService.java:24)
	at com.github.javafaker.Lorem.characters(Lorem.java:43)
	at com.github.javafaker.Internet.password(Internet.java:131)
```

**Versions:**
 - OS: Ubuntu 20.04 LTS
 - JDK 11.0.6
 - Faker Version 1.0.2

**Comment by Tavo5691** [comment]
I looked at @JinquanPeng 's  solution but I think a better solution would be to modify RandomService.nextInt so it defaults to 0 if the given number is less than 1. That way we can avoid the IllegalArgumentException.

I've opened a PR with the fix #580
