### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by poovaraj** [DiUS/java-faker#564]
**Bug**

The below error message is displayed while running java code.

Exception in thread "main" java.lang.NoSuchMethodError: org.yaml.snakeyaml.Yaml.loadAs(Ljava/io/InputStream;Ljava/lang/Class;)Ljava/lang/Object;
	at com.github.javafaker.service.FakeValues.loadValues(FakeValues.java:73)
	at com.github.javafaker.service.FakeValues.get(FakeValues.java:49)
	at com.github.javafaker.service.FakeValuesGrouping.get(FakeValuesGrouping.java:25)
	at com.github.javafaker.service.FakeValuesService.fetchObject(FakeValuesService.java:193)
	at com.github.javafaker.service.FakeValuesService.safeFetch(FakeValuesService.java:159)
	at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:305)
	at com.github.javafaker.Name.name(Name.java:29)
	at com.github.javafaker.Name.fullName(Name.java:54)

**To Reproduce**
Code to reproduce

                ```
                Faker faker = new Faker();
		String name = faker.name().fullName(); // Miss Samanta Schmidt
		String firstName = faker.name().firstName(); // Emory
		String lastName = faker.name().lastName(); // Barton

		String streetAddress = faker.address().streetAddress(); // 60018 Sawayn Brooks Suite 449
		
		System.out.println(name);
```
	

**Expected behavior**

It should not be thrown any error message

**Versions:**
 - OS: Windows 10
 - JDK 1.8.0_191
 - Faker Version 1.0.2

**Comment by poovaraj** [comment]
It is working after adding below dependency

           <dependency>
			<groupId>org.yaml</groupId>
			<artifactId>snakeyaml</artifactId>
			<version>1.23</version>
		</dependency>
