### ISSUE TITLE
faker().address().countyByZipCode() returns Runtime exception

### ISSUE THREAD

**Issue by kerry-textiq** [DiUS/java-faker#702]
**Describe the bug**
With default locale,

faker().address().countyByZipCode(faker.address().zipCode())

returns
java.lang.RuntimeException: address.county_by_postcode.39347 resulted in null expression

**To Reproduce**
Code to reproduce

**Expected behavior**

expect return country by zip code

**Versions:**
 - OS: [e.g. OSX] linux
 - JDK 8
 - Faker Version [e.g. 22] 1.0.2

**Additional context**

**Comment by jguthrie100** [comment]
Quick fix for now, for US addresses - you need to initialize Faker with:

`new Faker(new Locale("en-US"))`

**Comment by JosepMariaGomez** [comment]
**Describe the bug**

Exception retreiving county by zipcode

**Returns**

Exception in thread "main" java.lang.RuntimeException: address.county_by_postcode.57832 resulted in null expression
	at com.github.javafaker.service.FakeValuesService.resolve(FakeValuesService.java:308)
	at com.github.javafaker.Address.countyByZipCode(Address.java:43)
	at com.mycompany.fakergenerator.Main.main(Main.java:34)
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**To Reproduce**

```
        RandomService randomService = new RandomService();
        FakeValuesService fakeValuesService = new FakeValuesService(new Locale("es-ES"), randomService);

        Faker fkr = new Faker(fakeValuesService, randomService);
        for (int i = 0; i < 10; i++) {
            
            var first = fkr.name().firstName();

            var last = fkr.name().lastName();
            var address = fkr.address().streetName() + ", " + fkr.address().streetAddressNumber();
            var zipCode = fkr.address().zipCode();
            var pob = fkr.address().countyByZipCode(zipCode);
           System.out.println("");
     }
```
also

```
        Faker fkr = new Faker(new Locale("es-ES"));
        for (int i = 0; i < 10; i++) {
            
            var first = fkr.name().firstName();

            var last = fkr.name().lastName();
            var address = fkr.address().streetName() + ", " + fkr.address().streetAddressNumber();
            var zipCode = fkr.address().zipCode();
            var pob = fkr.address().countyByZipCode(zipCode);
           System.out.println("");
     }

```

**Expected behavior**

expect return county by postal code

**Versions:**

OS: Fedora 35
JDK 11
Faker Version 1.0.2

**Additional context**
